@server = http://localhost:4004
@auth = Authorization: Basic alice:

### Main.Customers
GET {{server}}/main/Customers
Content-Type: application/json
{{auth}}

### Main.Customers
POST {{server}}/main/Customers
Content-Type: application/json
{{auth}}

{
    "name": "Antonio",
    "age": 22
}

### Main.Customers
PATCH  {{server}}main/Customers(1)
Content-Type: application/json
{{auth}}

{
    "name": "Cícero",
    "age": 22
}

### Main.Customers
DELETE  {{server}}/main/Customers(1)
Content-Type: application/json
{{auth}}

