@server = http://localhost:4004
@auth = Authorization: Basic alice:

### Main.Customers
GET {{server}}/main/Customers
Content-Type: application/json
{{auth}}

### Main.Customers
GET {{server}}/main/Customers?$expand=orders
Content-Type: application/json
{{auth}}

### Main.Customers
POST {{server}}/main/Customers
Content-Type: application/json
{{auth}}

{
    "name": "Antonio",
    "age": 22
}

### Main.Customers
PATCH  {{server}}main/Customers(1)
Content-Type: application/json
{{auth}}

{
    "name": "Cícero",
    "age": 22
}

### Main.Customers
DELETE  {{server}}/main/Customers(1)
Content-Type: application/json
{{auth}}

### Main.Orders
GET {{server}}/main/Orders
Content-Type: application/json
{{auth}}

### Main.Orders
GET {{server}}/main/Orders?$expand=customer
Content-Type: application/json
{{auth}}

### Main.Orders
POST {{server}}/main/Orders
Content-Type: application/json
{{auth}}

{
    "amount": 20.00,
    "customer_ID": "11dc51f5-247a-442a-a107-b811df288529"
}